libusbemu: fix missing int types when compiling under mingw
Fix errors like:

platform/windows/libusb10emu/libusb-1.0/libusb.h:69: error: ‘uint8_t’ has not been declared
platform/windows/libusb10emu/libusb-1.0/libusb.h:69: error: ‘uint8_t’ has not been declared
platform/windows/libusb10emu/libusb-1.0/libusb.h:69: error: ‘uint16_t’ has not been declared
platform/windows/libusb10emu/libusb-1.0/libusb.h:69: error: ‘uint16_t’ has not been declared
...

Unfortunately it looks like not all Visual Studio versions provide
stdint.h, so hack around them.

Signed-off-by: Antonio Ospite <ospite@studenti.unina.it>